# 磁気センサキャリブレーション用パラメータ
# 磁気センサデータから張力を計算するためのパラメータを設定します。
# 順番はモータのIDに従ってください。

# センサ数
sensor_count: 9

# ばね定数 [N/m]
spring_constants: 0.67

# 磁束密度 [mT]
# 計測点[0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5][mm]における磁束密度
# D6[mm]、H3[mm]
# https://www.magtec.co.jp/simulation/
magnet_strength: [399.47, 331.09, 266.51, 210.82, 165.58, 130.11, 102.8, 81.9, 65.88, 53.54, 43.94]

# 磁石と磁気センサの距離 [mm]
# 磁石と磁気センサの距離は、センサ数と同じ数だけ必要
magnet_distances: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]

# モータ側ワイヤ角度 [deg]
# モータ側ワイヤ角度は、水平線からの絶対値とする
# sensor_countと同じ数だけ必要
motor_side_wire_angles: [0.0, 2.09, 4.19, 6.28, 8.38, 10.47, 12.57, 14.66, 16.76]

# マニピュレータ側ワイヤ角度 [deg]
# マニピュレータ側ワイヤ角度は、水平線からの絶対値とする
# sensor_countと同じ数だけ必要
manipulator_side_wire_angles: [0.0, 2.09, 4.19, 6.28, 8.38, 10.47, 12.57, 14.66, 16.76]

# 使用するモータの型番
motor_model-name: "XL330-M288-T"
# トルク [Nm]
motor_stall-torque: 0.52
# 最大定格電流 [A]
motor_stall-current: 1.47
# モータの無負荷回転数 [rpm]
motor_no-load-speed: 104.0
# モータの無負荷電流 [A]
motor_no-load-current: 0.15
# プーリ径 [m]
motor_pulley-dia: 0.015
